server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/fatcat?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: redis
    port: 6379
    password: 123456
    database: 1
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 100
        max-wait: 10000

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: 123456
    virtual-host: fatcat
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

  elasticsearch:
    rest:
      uris: elasticsearch:9200

  mail:
    host: smtp-mail.outlook.com
    username: ${SPRING_MAIL_USERNAME:邮箱}
    password: ${SPRING_MAIL_PASSWORD:密码}
    default-encoding: UTF-8
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

search:
  mode: elasticsearch

upload:
  mode: minio
#  oss:
#    url: http://Bucket域名/
#    endpoint: OSS配置endpoint
#    accessKeyId: OSS配置accessKeyId
#    accessKeySecret: OSS配置accessKeySecret
#    bucketName: OSS配置bucketName
  minio:
    url: http://localhost:9000/
    endpoint: http://localhost:9000
    accesskey: minioadmin
    secretKey: Dududu951221
    bucketName: test

website:
  url: https://junkangd.xmdev.cloud.com

qq:
  app-id: QQ APPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}

logging:
  file:
    name: /logs/app.log # name 优先级大于 path
#    path: /var/logs/myapp
  level:
    root: DEBUG
    com:
      aurora: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always
    mail:
      enabled: false  # 禁用邮件健康检查